name: Publish NuGet.org

on:
  push:
    branches: 
      - master
      
jobs:
  build:
    runs-on: windows-latest
    name: Update package

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Use .NET Core 3.1.301
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Building
      run: |
        dotnet build AmberCastle.WPF.Styles/AmberCastle.WPF.Styles.csproj -c Release
        dotnet build Tests/AmberCastle.WPF.Styles.Tests/AmberCastle.WPF.Styles.Tests.csproj -c Release
      
    - name: Testing
      run: dotnet test Tests/AmberCastle.WPF.Styles.Tests/AmberCastle.WPF.Styles.Tests.csproj

    - name: Packing
      run: dotnet pack AmberCastle.WPF.Styles/AmberCastle.WPF.Styles.csproj --no-build -c Release  -v q
      
    - name: Publishing
      run: dotnet nuget push AmberCastle.WPF.Styles/bin/Release/*.nupkg -k ${{ secrets.NuGetApiKey }} -n --skip-duplicate -s https://api.nuget.org/v3/index.json
